export interface UsuarioI{
    idusuario?: number,
    email?: string,
    password?: string,
    nombres?:string,
    apellidos?:string,
    rol?: string,
    direccion?:string,
    fechaNacimiento?:string,
    educacion?:string,
    genero?:string,
    vacunaCovid?:string,
    cv?:string,
    foto?:string,
    fechaCreacion?: string,
    confirm?: string,
}  